server:
  port: 8083

thread-pool:
  psd:
    core-size: 2
    max-size: 4

  # 数据库连接池配置
spring:
  datasource:
    url: jdbc:postgresql://192.168.197.130:5432/postgres
    username: postgres
    password: root1234
    initial-size: 1
    max-active: 1
    min-idle: 1
    #quartz
    quartz:
      initial-size: 1
      max-active: 1
      min-idle: 1
      password: root1234
      url: jdbc:postgresql://192.168.197.130:5432/lize_quartz
      username: postgres

  #cron
quartz:
  analysis:
    cronExpression: 0 */1 * * * ?

# MyBatis 配置
mybatis:
  mapper-locations: classpath:mapper/*.xml
 # config-location: classpath:mybatis-config.xml

# 配置打印sql
logging:
  level:
    com.tinet.lize.mapper: DEBUG